In [1]:
import numpy as np
import pandas as pd

In [2]:
# series: array 1 chieu
# dataframe: array 2 chieu

In [2]:
ser = pd.Series([1,2,3,4,5,6,7,8,9,10,11,12,13])
ser2=ser.map(lambda x:x*x)
ser2

0       1
1       4
2       9
3      16
4      25
5      36
6      49
7      64
8      81
9     100
10    121
11    144
12    169
dtype: int64

In [3]:
type(ser)

pandas.core.series.Series

In [4]:
ser.dtype

dtype('int64')

In [5]:
ser

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
dtype: int64

In [6]:
ser[1]

np.int64(2)

In [7]:
ser.head()

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [8]:
ser.tail()

8      9
9     10
10    11
11    12
12    13
dtype: int64

In [9]:
ser.head(10)

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [11]:
lst = range(20)
print(list(lst))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [12]:
for i in range(20):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19

In [13]:
lst = [3.5, 6.7, 4.8, 8.6, 7.2]
lst

[3.5, 6.7, 4.8, 8.6, 7.2]

In [15]:
arr = np.array(lst)
arr

array([3.5, 6.7, 4.8, 8.6, 7.2])

In [16]:
ser = pd.Series(arr)

In [17]:
ser.tolist()

[3.5, 6.7, 4.8, 8.6, 7.2]

In [18]:
ser.values

array([3.5, 6.7, 4.8, 8.6, 7.2])

In [19]:
ser*2

0     7.0
1    13.4
2     9.6
3    17.2
4    14.4
dtype: float64

In [20]:
ser.mean()

np.float64(6.16)

In [21]:
ser.median()

np.float64(6.7)

In [22]:
ser.sum()

np.float64(30.8)

In [23]:
ser.std()

np.float64(2.015688467993008)

In [24]:
df = pd.DataFrame({'name':['Tom','Jack','Rose'], 'age':[24,32,17]})

In [25]:
df

   name  age
0   Tom   24
1  Jack   32
2  Rose   17

In [26]:
df.iloc[1]

name    Jack
age       32
Name: 1, dtype: object

In [27]:
type(df.iloc[1])

pandas.core.series.Series

In [28]:
df['name']

0     Tom
1    Jack
2    Rose
Name: name, dtype: object

In [29]:
type(df['name'])

pandas.core.series.Series

In [32]:
df['age']+3

0    27
1    35
2    20
Name: age, dtype: int64

In [33]:
df = pd.read_csv('drinks.csv', index_col=0)

FileNotFoundError: [Errno 2] No such file or directory: 'drinks.csv'

In [36]:
df.head()

   name  age
0   Tom   24
1  Jack   32
2  Rose   17

In [34]:
df.columns

Index(['name', 'age'], dtype='object')

In [35]:
df.shape

(3, 2)