In [2]:
import numpy as np
import pandas as pd

In [30]:
# tao series 
ser_diem = pd.Series([7.8, 6.7, 9.2])
isum=ser_diem.sum()
iaverage=ser_diem.mean()
imedian=ser_diem.median()
ser_diem[2]
imedian

7.8

In [4]:
type(ser_diem)

pandas.core.series.Series

In [5]:
ser_diem

0    7.8
1    6.7
2    9.2
3    8.3
4    5.4
dtype: float64

In [5]:
# index : number va label

In [19]:
ser_diem = pd.Series([7.8, 6.7, 9.2, 8.3, 5.4], index=['A01', 'A02', 'B03', 'B04', 'C05'])
ser_diem['A05']=10

ser_diem

A01     7.8
A02     6.7
B03     9.2
B04     8.3
C05     5.4
A05    10.0
dtype: float64

In [7]:
ser_diem

A01    7.8
A02    6.7
B03    9.2
B04    8.3
C05    5.4
dtype: float64

In [8]:
ser_diem['B03']

9.2

In [9]:
ser_diem[0]

7.8

In [21]:
ser_diem.head(3)

A01    7.8
A02    6.7
B03    9.2
dtype: float64

In [22]:
ser_diem.tail(3)

B04     8.3
C05     5.4
A05    10.0
dtype: float64

In [23]:
ser_diem.shape

(6,)

In [24]:
ser_diem.size

6

In [11]:
dict_1={'a':"amy",'b':100,'c':1000}
sd1=pd.Series(dict_1)
sd1

a     amy
b     100
c    1000
dtype: object

In [16]:
ser_diem.tolist()  # method

[7.8, 6.7, 9.2, 8.3, 5.4]

In [17]:
ser_diem.values # property

array([7.8, 6.7, 9.2, 8.3, 5.4])

In [19]:
ser_diem_ = ser_diem.map(lambda x: x+0.5) # bieu thuc lambda

In [20]:
ser_diem

A01    7.8
A02    6.7
B03    9.2
B04    8.3
C05    5.4
dtype: float64

In [21]:
ser_diem_

A01    8.3
A02    7.2
B03    9.7
B04    8.8
C05    5.9
dtype: float64

In [22]:
def myfunc(x):
    return x*x

In [23]:
ser_diem.map(myfunc) # map, apply

A01    60.84
A02    44.89
B03    84.64
B04    68.89
C05    29.16
dtype: float64

In [24]:
def myfunc(x):
    if x>=8:
        return x*x
    else:
        return x

In [25]:
ser_diem.map(myfunc)

A01     7.80
A02     6.70
B03    84.64
B04    68.89
C05     5.40
dtype: float64

In [27]:
ser_diem

A01    7.8
A02    6.7
B03    9.2
B04    8.3
C05    5.4
dtype: float64

In [32]:
ser_note = np.where(ser_diem>=5,"Dat","Rot")

In [33]:
df = pd.DataFrame({'diem':ser_diem, 'note':ser_note})

In [30]:
df

     diem note
A01   7.8  Dat
A02   6.7  Dat
B03   9.2  Dat
B04   8.3  Dat
C05   5.4  Dat

In [31]:
ser = pd.Series([1,2,3,2,5,6])
ser

0    1
1    2
2    3
3    2
4    5
5    6
dtype: int64

In [32]:
ser.mode()

0    2
dtype: int64

In [33]:
ser.sum()

19

In [34]:
ser.cumsum()

0     1
1     3
2     6
3     8
4    13
5    19
dtype: int64

In [35]:
ser_diem

A01    7.8
A02    6.7
B03    9.2
B04    8.3
C05    5.4
dtype: float64

In [36]:
ser_diem.describe()

count    5.000000
mean     7.480000
std      1.472073
min      5.400000
25%      6.700000
50%      7.800000
75%      8.300000
max      9.200000
dtype: float64

In [37]:
ser_diem.mean()

7.4799999999999995

In [38]:
ser_diem.median()

7.8

In [35]:
lst=[1,2,3]
pd1=pd.DataFrame(lst,columns=['So'])
pd1

   So
0   1
1   2
2   3

In [36]:
lst2=[['Mary',20],['Jony',21],['Tom',22]]
pd2=pd.DataFrame(lst2,columns=['Name','Age'])
pd2

   Name  Age
0  Mary   20
1  Jony   21
2   Tom   22